version: '3'

services:
  nuxt:
    container_name: nuxt
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3000:3000'
      - '24678:24678'
